export const ErrorCodes = {
  // Anime
  ANIME_NOT_FOUND: 'ANIME_NOT_FOUND',
  ANIME_INVALID_ID: 'ANIME_INVALID_ID',

  // Music
  MUSIC_NOT_FOUND: 'MUSIC_NOT_FOUND',
  MUSIC_INVALID_ID: 'MUSIC_INVALID_ID',

  // Watch
  WATCH_STATE_NOT_FOUND: 'WATCH_STATE_NOT_FOUND',

  // Collections
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',

  // Auth / Access
  AUTH_REQUIRED: 'AUTH_REQUIRED', // 401
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN', // 401
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED', // 401
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN', // 403

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Infra
  DB_ERROR: 'DB_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INVALID_ID: 'USER_INVALID_ID',
  USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',

  // Generic
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  INVALID_IMAGE_PATH: 'INVALID_IMAGE_PATH',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
